/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "NeonLibs"

include("plugin")
include("project:module-hook")
include("project:module-smtp")
include("project:module-common")
include("common-env")